name: Build-Work

on:
  push:
    branches: main
  pull_request:
    branches: main
    types: [opened, synchronize, reopened]
  
permissions:
  contents: read


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.0.0, 2.7.2]
    
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up ruby
      uses: ruby/setup-ruby@v3
      with:
        ruby-version: ${{matrix.ruby-version}}
        bundler-cache: true
    - name: Run Tests
      run: bundle exec rake spec    
